# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: preproc_gibbs
description: Remove Gibbs Ringing Artifacts
keywords:
  - correction
  - Gibbs
  - artefact
tools:
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      doi: 10.1016/j.neuroimage.2019.116137
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti image file to correct
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  dwi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*dwi_gibbs_corrected.nii.gz":
          type: file
          description: DWI image Gibbs corrected
          pattern: "*dwi_gibbs_corrected.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@arnaudbore"
