# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: utils_extractb0
description: Extract a b0 volume from a DWI image.
keywords:
  - dwi
  - extract
  - b0
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
args:
  - extraction_strategy:
    type: string
    description: |
      Extract either:
      all b0 (all),
      mean b0 (mean),
      mean of each continuous cluster of b0s (cluster-mean),
      first b0 of each continuous cluster of b0s (cluster-first).
    default: mean
    choices: all, mean, cluster-mean, cluster-first
  - b0_threshold:
    type: integer
    description: Threshold under which b-values are considered to be b0s.
    default: 20
  - output_series:
    type: boolean
    description: |
      If output b0 volume has multiple time points, only outputs a single
      image instead of a numbered series of images.scil_dwi_extract_b0
    default: false
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI volume to perform BET + crop.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
output:
  b0:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_b0*.nii.gz":
          type: file
          description: b0 image(s) extracted from the DWI
          pattern: "*_b0*.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@AlexVCaron"
