# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: preproc_normalize
description: Normalize DWI using MRtrix3 (in WM)
keywords:
  - nifti
  - normalise
  - scilpy
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
  - MRtrix3:
      description: |
        MRtrix3 is a software package for various types of diffusion imaging
        data, including diffusion-weighted, diffusion-tensor, and q-ball imaging.
      homepage: https://www.mrtrix.org/
      doi: 10.1016/j.neuroimage.2019.116137
      identifier: ""
args:
  - dwi_shell_tolerance:
      type: integer
      description: |
        Tolerance in s/mm2 for grouping b-values into shells.
        E.g. with a tolerance of 20, b-values between 0 and 20 will be considered
        as b=0.
      default: None
  - fa_mask_threshold:
      type: float
      description: Threshold to apply on the FA map to create a white matter mask.
      default: None
  - max_dti_shell_value:
      type: integer
      description: |
        Maximum b-value to use for DTI fitting. All shells under this value will
        be used.
    default: 1600
  - dti_shells:
      type: string
      description: |
        Space separated list of b-values to use for DTI fitting. If None, all shells
        under max_dti_shell_value will be used.
      default: None
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti image file to normalize
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: Text file containing b-values
        pattern: "*.{.bval}"
        ontologies: []
    - bvec:
        type: file
        description: Text file containing b-vectors
        pattern: "*.{.bvec}"
        ontologies: []
    - mask:
        type: file
        description: Nifti image file used to mask the input image
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  dwi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*dwi_normalized.nii.gz":
          type: file
          description: Normalized Nifti image file
          pattern: "*dwi_normalized.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  mask:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*fa_wm_mask.nii.gz":
          type: file
          description: Nifti image file mask
          pattern: "*fa_wm_mask.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@scilus"
