# yaml-language-server: $schema=https://raw.githubusercontent.com/scilus/nf-neuro/main/modules/meta-schema.json
name: "preproc_topup"
description: |
  Run magnetic susceptibility distortions correction using FSL Topup. The module can take either
  b0 or DWI volumes. The latter activates b0 extraction prior to running Topup. Extraction can be
  configured to take one (default) or many b0 volumes in each forward and reverse acquired DWI and
  perform averaging if needed. Note that running Topup with more than one volume per encoding
  direction greatly increases computation time.
keywords:
  - DWI
  - distorsion
  - topup
tools:
  - ANTs:
      description: Advanced Normalization Tools (ANTs) for image processing.
      homepage: http://stnava.github.io/ANTs/
      doi: "10.1038/s41598-021-87564-6"
      identifier: ""
  - FSL:
      description: FSL Toolbox
      homepage: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki
      doi: 10.1016/j.neuroimage.2011.09.015
      identifier: ""
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: DWI Nifti image
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format [DWI].
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-values in FSL format [DWI].
        pattern: "*.bvec"
        ontologies: []
    - b0:
        type: file
        description: b0 [DWI].
        pattern: "*.bvec"
        ontologies: []
    - rev_dwi:
        type: file
        description: DWI Nifti image [rev-DWI].
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - rev_bval:
        type: file
        description: B-values in FSL format [rev-DWI].
        pattern: "*.bval"
        ontologies: []
    - rev_bvec:
        type: file
        description: B-vectors in FSL format [rev-DWI].
        pattern: "*.bvec"
        ontologies: []
    - rev_b0:
        type: file
        description: Reversed b0 [rev-DWI].
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
  - config_topup:
      type: file
      description: topup config file. See https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide#Configuration_files
      pattern: "*cnf"
      ontologies: []
args:
  - encoding:
      type: string
      description: Encoding direction of the forward DWI.
      choices: "x, y, z"
      default: "y"
  - readout:
      type: float
      description: Total readout time from the DICOM metadata.
      default: 0.062
  - b0_thr_extract_b0:
      type: integer
      description: Threshold under which b-values are considered to be b0s.
      default: 10
  - prefix_topup:
      type: string
      description: Prefix to prepend to Topup output files.
  - default_config_topup:
      type: string
      description: Default Topup configuration to use.
      choices: "b02b0.cnf, b02b0_1.cnf, b02b0_2.cnf, b02b0_4.cnf, b02b0_7T.cnf"
      default: "b02b0.cnf"
  - run_qc:
      type: boolean
      description: Run quality control.
      default: true
output:
  topup_corrected_b0s:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__corrected_b0s.nii.gz":
          type: file
          description: Nifti volume - b0 corrected
          pattern: "*__corrected_b0s.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  topup_fieldcoef:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_fieldcoef.nii.gz":
          type: file
          description: Nifti volume - topup field to correct for distorsion
          pattern: "*_fieldcoef.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  topup_movpart:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_movpar.txt":
          type: file
          description: Text file - topup movpart
          pattern: "*_movpar.txt"
          ontologies: []
  rev_b0_warped:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__rev_b0_warped.nii.gz":
          type: file
          description: Nifti volume - rev b0 warped on b0
          pattern: "*__rev_b0_warped.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  rev_b0_mean:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__rev_b0_mean.nii.gz":
          type: file
          description: Nifti volume - rev b0 mean
          pattern: "*__rev_b0_mean.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  b0_mean:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__b0_mean.nii.gz":
          type: file
          description: Nifti volume - b0 mean
          pattern: "*__b0_mean.nii.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  mqc:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_b0_topup_mqc.gif":
          type: file
          description: |
            .gif file containing quality control image for the topup process
            (Comparison with dwi and rev_dwi). Made for use in MultiQC report.
          pattern: "*_b0_topup_mqc.gif"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions.
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@arnaudbore"
