# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: reconst_frf
description: Compute a Fiber Response Function (FRF) from a DWI. Note that multiple
  types of FRF are available through the method argument. The single-shell single-tissue
  (ssst) FRF is performed by choosing the ssst method (task.ext.method). This is expected
  to output a single WM FRF. The multi-shell multi-tissue (msmt) FRF is performed
  by choosing the msmt method (task.ext.method). This is expected to output a WM FRF,
  a GM FRF and a CSF FRF, each containing values for every shells.
keywords:
  - Fiber Orientation Distribution Function
  - Diffusion MRI
  - Fiber Response Function
tools:
  - DIPY:
      description: DIPY is the paragon 3D/4D+ imaging library in Python.
      homepage: https://dipy.org
      identifier: ""
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti image of DWI.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
    - mask:
        type: file
        description: Nifti b0 binary mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - wm_mask:
        type: file
        description: Nifti binary WM mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - gm_mask:
        type: file
        description: Nifti binary GM mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - csf_mask:
        type: file
        description: Nifti binary CSF mask.
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
output:
  frf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__frf.txt":
          type: file
          description: Fiber Response Function (FRF), in the case of ssst_frf.
          pattern: "*__frf.txt"
          ontologies: []
  wm_frf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__wm_frf.txt":
          type: file
          description: WM Fiber Response Function (FRF), in the case of msmt_frf.
          pattern: "*__wm_frf.txt"
          ontologies: []
  gm_frf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__gm_frf.txt":
          type: file
          description: GM Fiber Response Function (FRF), in the case of msmt_frf.
          pattern: "*__gm_frf.txt"
          ontologies: []
  csf_frf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__csf_frf.txt":
          type: file
          description: CSF Fiber Response Function (FRF), in the case of msmt_frf.
          pattern: "*__csf_frf.txt"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@Manonedde"
  - "@karanphil"
